module.exports = {
    packagerConfig: {
        asar: true
    },
    makers: [
        {
            name: "@electron-forge/maker-squirrel",
            config: {
                name: "mcl"
            }
        },
        {
            name: "@electron-forge/maker-zip",
            platforms: [
                "darwin"
            ]
        },
        {
            name: "@electron-forge/maker-deb",
            config: {}
        },
        {
            name: "@electron-forge/maker-rpm",
            config: {}
        }
    ],
    publishers: [
        {
            name: "@electron-forge/publisher-github",
            config: {
                repository: {
                    owner: "jakeyizle",
                    name: "mcl"
                }
            }
        }
    ],
    hooks: {
        postMake: function (forgeConfig, outputs) {
            // outputs are the paths to files that are generated by make, like Squirrel's .exe & RELEASES
            // adapt the atom code here and return outputs
            console.log('POSTMAKE');
            console.log(forgeConfig);
            console.log(outputs);
            return Promise.resolve(modified_outputs);
          }
    }
}
